### ISSUE TITLE
[deoplete] Could not get completions from: clang2

### ISSUE THREAD

**Issue by teto** [tweekmonster/deoplete-clang2#16]
While working on neovim code and trying to change a member variable `myStruct.XXX` (deoplete trying to complete XXX):

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/teto/.local/share/nvim/site/pack/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 118, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/teto/.local/share/nvim/site/pack/deoplete-clang2/rplugin/python3/deoplete/sources/deoplete_clang2.py", line 659, in gather_candidates
[deoplete]     cmd, flags = self.build_flags(context)
[deoplete]   File "/home/teto/.local/share/nvim/site/pack/deoplete-clang2/rplugin/python3/deoplete/sources/deoplete_clang2.py", line 502, in build_flags
[deoplete]     flags = self.get_clang_flags(lang) + flags
[deoplete]   File "/home/teto/.local/share/nvim/site/pack/deoplete-clang2/rplugin/python3/deoplete/sources/deoplete_clang2.py", line 223, in get_clang_flags
[deoplete]     stdout = self.call_clang([], clang_flags, True)
[deoplete]   File "/home/teto/.local/share/nvim/site/pack/deoplete-clang2/rplugin/python3/deoplete/sources/deoplete_clang2.py", line 300, in call_clang
[deoplete]     stderr=subprocess.PIPE, cwd=cwd)
[deoplete]   File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
[deoplete]     restore_signals, start_new_session)
[deoplete]   File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
[deoplete]     raise child_exception_type(errno_num, err_msg)
[deoplete] PermissionError: [Errno 13] Permission denied
[deoplete] Could not get completions from: clang2.  Use :messages for error details.
```
A priori all files belong to the current user.

**Comment by tweekmonster** [comment]
I believe the permission error refers to the execution bit, not the file ownership.  You should check `g:deoplete#sources#clang#executable` or check `:!which -a clang`.

**Comment by teto** [comment]
`which -a clang` returns /usr/bin/clang so nothing exotic.
I've just set `g:deoplete#sources#clang#executable` just in case but should I need to considering:
`Note: For simple projects, you probably don't need to configure anything. You definitely shouldn't need to configure anything if your project uses a compilation database.`

I'll see if it gets reproduced with `g:deoplete#sources#clang#executable` set.

**Comment by tweekmonster** [comment]
Yeah try setting the full executable path.  It might be that it's simply using `clang` and it isn't found in `$PATH` for some reason.  Is this happening under specific conditions or did this start happening for everything all of the sudden?

**Comment by teto** [comment]
Hasn't happened since then :s

**Comment by KmBKeef** [comment]
happened with me but after removing ale(neomake alternative) the issue was resolved somehow
