### ISSUE TITLE
Issue with UltiSnips snippets

### ISSUE THREAD

**Issue by HiPhish** [tweekmonster/deoplete-clang2#3]
I have a snippet that expands
```c
if
```
to
```c
if (true) {
	
}
```
However, when I also use deoplete-clang it expands to
```c
if<Plug>delimitMateS-Tab
```
instead. The problem persists regardless of my UltiSnips settings, and it doesn't happen with deoplete-clang.

**Comment by tweekmonster** [comment]
Hrm.  Could you post the value of `b:clang2_orig_maps`?

**Comment by tweekmonster** [comment]
I found the issue.  I'm trying some things out to see if I can fix it.
