### ISSUE TITLE
Objc methods in my own code not work

### ISSUE THREAD

**Issue by orklann** [tweekmonster/deoplete-clang2#39]
Hi, everything works for built-in Objc methods, like NSString, NSArray, NSView, etc, but how can i make it also autocomplete my own code in my Xcode project, I have a lot of objc classes, which can not autocomplete.

I setup this plugin in Vim 9, like that say in the README.md, and the only thing I make is adding below line to the .clang file in the root of my project.

`-darwin=14.5`

My questions is, how can I also autocomplete my own objc calls, not only the built-in objc calls.

Thank you for the great plugin.

**Comment by Shougo** [comment]
Sorry.  The plugin is very old and it is not supported.

You should use `ddc.vim` instead.

**Comment by orklann** [comment]
Thank you for the quick reply, does ddc.vim works with Objc completion?

**Comment by orklann** [comment]
I switch to neovim, and your plugin works fine, but there is one bug:
Everytime I edit a .h/.m file, and enter insert mode (press a or i) the first time, it always throws this erorr:

```
Error detected while processing InsertEnter Autocommands for "<buffer=5>"..funct
ion <SNR>84_steal_keys[15]..<SNR>84_maparg:
line    9:
E716: Key not present in Dictionary: "rhs"
```

**Comment by Shougo** [comment]
> Thank you for the quick reply, does ddc.vim works with Objc completion?

You need to use LSP completion like this.
https://github.com/MaskRay/ccls

> I switch to neovim, and your plugin works fine, but there is one bug:
> Everytime I edit a .h/.m file, and enter insert mode (press a or i) the first time, it always throws this erorr:

Sorry.  I don't know.  Because it is not my plugins' feature.
I don't define the `maparg()` function.

**Comment by orklann** [comment]
Hi, I just found a define of `maparg()` in your code:

https://github.com/tweekmonster/deoplete-clang2/blob/338f28b077aa0493707e5fa0a2f5bfab46fa5c16/autoload/clang2.vim#L225

I think that may cause the issue.

**Comment by orklann** [comment]
Sorry, I just fixed it, I remove one of my plugin, and reinstall all plugins, and it works fine now. Thank you for the greate plugin.
