### ISSUE TITLE
Insert mode `<tab>` cause wrong input.

### ISSUE THREAD

**Issue by wsdjeg** [tweekmonster/deoplete-clang2#6]
1. open new empty c file, `nvim main.c`
2. go to insert mode, type `<tab>`

you will see `pumvisible() ? "\" : ""` be inserted.

**Comment by tweekmonster** [comment]
I thought this was fixed in #4?  Do you know what plugin that originates from?

**Comment by wsdjeg** [comment]
@tweekmonster 
I just check the verbose, it should be clang2, sorry, I think I am using old version of deoplete-clang2. I just test the latest version, it works well for me, sorry for invalid issue.
```
:Verbose imap <tab>

i  <Tab>       *@<SNR>176_select_placeholder("i", 1)
	Last set from ~/.cache/vimfiles/.cache/init.vim/.dein/autoload/clang2.vim
i  <Tab>         SpaceVim#mapping#tab()
	Last set from ~/SpaceVim/SpaceVim/autoload/SpaceVim/default.vim
```

**Comment by tweekmonster** [comment]
@wsdjeg Oh okay.  No problem!  I thought it was another issue with `\` in double quotes.  Good to know it's working :D
